### ISSUE TITLE
python3, not python

### ISSUE THREAD

**Issue by CoolHandSquid** [nikhilakki/pdf2jpg#1]
The documentation states that you are to use python. The code is written in python3.

**Comment by nikhilakki** [comment]
if you use [pipenv](https://pypi.org/project/pipenv/), install required dependencies with ```pipenv install``` and then run ```pipenv run python <replace with script.py>```

___Note___ _- I haven't updated the scripts in a long time, it's better to use [pdf2image](https://pypi.org/project/pdf2image/) as this repo just contains wrapper scripts._
